<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ManageBooking.aspx.cs" Inherits="WebApplication1.Account.ManageBooking" %>
<%@ Register Src="~/Account/OpenAuthProviders.ascx" TagPrefix="uc" TagName="OpenAuthProviders" %>
<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <h2><%: Title %></h2>
    <p class="text-danger">
        <asp:Literal runat="server" ID="ErrorMessage" />
    </p>

    <div class="form-horizontal">
      
        <hr />
        <div class="form-group">
            <asp:Label runat="server" AssociatedControlID="GridView2">Recently Added Sessions</asp:Label><br>
                        <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" OnSelectedIndexChanged="GridView2_SelectedIndexChanged" AutoGenerateEditButton="True" AutoGenerateDeleteButton="true"
        AllowPaging="true" OnRowEditing="GridView2_RowEditing" OnRowUpdating="GridView2_RowUpdating" OnRowDeleting="GridView2_RowDeleting">
                            <Columns>
                                <asp:BoundField DataField="Name" HeaderText="Name" />
                                <asp:BoundField DataField="SessionDate" HeaderText="Session Date" />
                                <asp:BoundField DataField="Email" HeaderText="Email" />
                                <asp:BoundField DataField="Time" HeaderText="Time" />
                                <asp:BoundField DataField="Status" HeaderText="Status" />
                            </Columns>
                        </asp:GridView>
                </div>      
        </div>   
        <div class="form-group">
            <asp:Label runat="server" CssClass="col-md-2 control-label">Manage Another Booking </asp:Label><br>
        <div class="col-md-10">
                
            </div>
        </div>
        <div class="form-group">
            <asp:Label ID="Email" runat="server" CssClass="col-md-2 control-label">Email </asp:Label>
            <div class="col-md-10">
                    <asp:TextBox ID="EmailID" runat="server"></asp:TextBox>
                     <asp:RequiredFieldValidator runat="server" ControlToValidate="EmailID"
                        CssClass="text-danger" ErrorMessage="The Email Address field is required." />
            </div>
        </div>
       
        <div class="form-group">
            
                <asp:Button ID="Search" runat="server" Text="Search" OnClick="Search_Click" />
           
        </div>
        <div class="form-group">
                    <div class="col-md-10">
                        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AutoGenerateEditButton="True" AutoGenerateDeleteButton="true"
        AllowPaging="true" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" OnRowDeleting="GridView1_RowDeleting">
                            <Columns>
                                <asp:BoundField DataField="Name" HeaderText="Name" />
                                <asp:BoundField DataField="SessionDate" HeaderText="Session Date" />
                                <asp:BoundField DataField="Time" HeaderText="Time" />                     
                            </Columns>
                        </asp:GridView>
                    </div>  
    </div>
    </div>
</asp:Content>

